#DATABASE
services:
  mongo_db:
    image: mongo:4.4.6
    container_name: 'mongo_db'
    restart: always
    ports:
      - '27017:27017'
    networks:
      - custom
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

  #APP
  app:
    container_name: 'strava'
    image: strava
    environment:
      - MONGO_URI=mongodb://mongo_db/
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - custom
    depends_on:
      - mongo_db
    env_file:
      - .env
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  custom:
    driver: bridge